const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const installer = fs.readFileSync(path.join(__dirname, '..', 'build', 'installer.nsh'), 'utf8')
const cleanupOpenVpnGui = fs.readFileSync(path.join(__dirname, '..', 'build', 'cleanup-openvpn-gui.ps1'), 'utf8')

test('bundles the OpenVPN runtime and installs only the official Win7-compatible TAP MSI features', () => {
  assert.match(installer, /OpenVPN-2\.5\.10-I601-amd64\.msi/)
  assert.match(installer, /msiexec\.exe/)
  assert.match(installer, /ADDLOCAL=Drivers,Drivers\.TAPWindows6/)
  assert.doesNotMatch(installer, /ADDLOCAL=[^\r\n]*Drivers\.Wintun/)
  assert.doesNotMatch(installer, /ADDLOCAL=[^\r\n]*OpenVPN,Drivers/)
  assert.match(installer, /WEL-TAP-install\.log/)
  assert.match(installer, /tap-msi-2\.5\.10\.ready/)
  assert.match(installer, /StrCpy \$5 1\s+Goto prepare_tap/)
  assert.match(installer, /resources\\openvpn\\bin\\openvpn\.exe/)
  assert.match(installer, /tapctl\.exe" create --hwid "root\\tap0901" --name "WEL Virtual LAN"/)
  assert.match(installer, /\$APPDATA\\WELPlatform\\tap-create\.txt/)
  assert.match(installer, /FileWrite \$4 "\$3"/)
  assert.match(installer, /findstr\.exe" \/I \/L \/G:"\$APPDATA\\WELPlatform\\tap-create\.txt"/)
  assert.doesNotMatch(installer, /ensure-wel-tap\.ps1|remove-wel-tap\.ps1/)
})

test('reuses the dedicated adapter across upgrades without recreating it', () => {
  assert.match(installer, /tapctl\.exe" list .*findstr\.exe" \/L \/C:"WEL Virtual LAN" \/C:"WEL TAP"/)
  assert.doesNotMatch(installer, /wel-tapctl\.exe" delete|uninstall_wel_tap_loop/)
  assert.match(installer, /Keep the dedicated adapter across upgrades and reinstalls/)
  assert.doesNotMatch(installer, /Win32_NetworkAdapter|Get-NetAdapter/)
})

test('lets Win7 finish installation when a newly installed driver needs reboot', () => {
  assert.match(installer, /SetRebootFlag true/)
  assert.match(installer, /Windows 尚未完成虚拟网卡初始化/)
  assert.match(installer, /IntCmp \$4 20 tap_requires_reboot create_driver_tap tap_requires_reboot/)
  assert.doesNotMatch(installer, /WEL 虚拟网卡创建失败.*Abort/s)
})

test('runs installer system commands without visible console windows', () => {
  assert.doesNotMatch(installer, /ExecWait/)
  assert.match(installer, /nsExec::ExecToLog[^\n]+netsh\.exe/)
  assert.match(installer, /nsExec::ExecToLog[^\n]+powershell\.exe/)
})

test('removes unused OpenVPN GUI shortcuts and startup entries', () => {
  assert.match(installer, /cleanup-openvpn-gui\.ps1/)
  assert.match(installer, /\$SMSTARTUP\\OpenVPN GUI\.lnk/)
  assert.match(installer, /DeleteRegValue HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Run" "OpenVPN GUI"/)
  assert.match(installer, /DeleteRegValue HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Run" "OpenVPN GUI"/)
  assert.match(installer, /DeleteRegValue HKLM "Software\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Run" "OpenVPN GUI"/)
  assert.match(installer, /taskkill\.exe" \/F \/IM openvpn-gui\.exe/)
  assert.match(cleanupOpenVpnGui, /CommonStartup/)
  assert.match(cleanupOpenVpnGui, /Remove-ItemProperty/)
  assert.match(cleanupOpenVpnGui, /Get-ScheduledTask/)
  assert.match(cleanupOpenVpnGui, /Unregister-ScheduledTask/)
  assert.match(installer, /Sysnative\\WindowsPowerShell/)
  assert.match(installer, /SetRegView 64/)
  assert.match(installer, /SetRegView 32/)
})
